config/routes.rb
Rails.application.routes.draw do

	resources :users do
		resources :tips
	end

	devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
	
	root 'landing_pages#index'
	get 'landing_pages/index'
	get 'landing_pages/home'
	get 'landing_pages/stats'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    can :manage, User, id: user.id
  end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-AbilitiesS
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user

  scope :amount_desc, -> { order(amount: :desc) }
  scope :amount_asc, -> { order(amount: :asc) }

  def number_to_currency_zar
  	number_to_currency(number, :unit => "R", :separator => ",", :delimiter => ".")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :tips, dependent: :destroy

	def highest_tip_amount
	  tips.amount_desc.first
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	  def after_sign_in_path_for(resource_or_scope)
    if current_user.sign_in_count == 1
      edit_user_path(current_user)
    else
      landing_pages_home_path
    end
  end

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to main_app.root_url, alert: exception.message
	end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def index
  end

  def home
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
   @user = User.find(params[:user_id])
   @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
   @user = User.find(params[:user_id])
   @tip = @user.tips.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to user_tips_url, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to user_tips_url, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to user_tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @user = User.find(params[:user_id])
      @tip = Tip.find(params[:id])
      @tip.user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:user_id, :date, :hours, :amount, :comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to landing_pages_home_url, notice: 'User Account Successfully Created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to landing_pages_home_url, notice: 'You Have Successfully Updated Your Details.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Successfully Destroyed User Account.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing_pages/home.html.erb
  <div class="text-center">
    <h2>Hi <%= current_user.first_name %></h2>
    <h3>What would you like to do?</h3>
  </div>

  <div class="container top-buffer">
    <hr>
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3 text-center">
        <%= link_to "ADD A DAILY TIP", new_user_tip_path(current_user), class: 'btn btn-lg cmd-button' %>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3 text-center">
        <%= link_to "SEE ALL TIPS", user_tips_path(current_user), class: 'btn btn-lg cmd-button' %>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3 text-center">
        <%= link_to "SEE SOME STATS", landing_pages_stats_path, class: 'btn btn-lg cmd-button' %>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3 text-center">
        <%= link_to "CHECK MY WALLET", new_user_tip_path(current_user), class: 'btn btn-lg cmd-button' %>
      </div>
    </div>
  </div>

app/views/landing_pages/index.html.erb
<div class="top-buffer">
  <div class="text-center">
    <h1>The Waiter Log</h1>
  </div>
  <%= image_tag('the-waiter-log.png', class: 'mx-auto d-block') %>
</div>

app/views/landing_pages/stats.html.erb
<div class="text-center">
  <h2>Some Stats</h2>
  <hr>
</div>

app/views/layouts/_head.html.erb
<head>
  <%= favicon_link_tag asset_path('the-waiter-log.png', rel: 'icon', type: 'image/png') %>
  <title>TheWaiterLog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <!-- <link href="https://fonts.googleapis.com/css?family=Neucha|Amatic+SC" rel="stylesheet"> -->
  
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous"> -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm justify-content-center">
  <ul class="navbar-nav">
    <% if user_signed_in? %>

    <%= link_to('Home', landing_pages_home_path, class: "nav-item nav-link") %> 
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link") %>

    <% else %>

    <%= link_to('Sign Up', new_user_registration_path, class: "nav-item nav-link") %>
    <%= link_to('Login', new_user_session_path, class: "nav-item nav-link") %>

    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/head' %>

<body>

  <%= render 'layouts/nav' %>

  <div class="flash-notices text-center">
    <% if notice %>
    <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
    <% end %>

    <%if alert %>
    <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
  </div>

    <%= yield %>

  </div> <!-- end container-fluid -->

</body>
</html>

app/views/tips/_form.html.erb
<div class="container">
  <hr>
  <%= form_for [@user, @tip] do |f| %>
  <% if @tip.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

    <ul>
      <% @tip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, class: 'sr-only' %>
    <div class="input-group mb-2">
      <div class="input-group-prepend" id="date-addon">
        <span class="input-group-text far fa-calendar-alt"></span>
      </div>
      <%= f.date_select :date, class: 'form-control form-control-lg', 'aria-label': 'date', 'aria-described-by': 'date-addon' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hours, class: 'sr-only' %>
    <div class="input-group mb-2">
      <div class="input-group-prepend" id="hours-addon">
        <span class="input-group-text far fa-clock"></span>
      </div>
      <%= f.number_field :hours, class: 'form-control form-control-lg', 'aria-label': 'hours', 'aria-describedby': 'hours-addon', placeholder: 'Hours Worked' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :amount, class: 'sr-only' %>
    <div class="input-group mb-2">
      <div class="input-group-prepend" id="amount-addon">
        <span class="input-group-text far fa-money-bill-alt"></span>
      </div>
      <%= f.text_field :amount, class: 'form-control form-control-lg', 'aria-label': 'amount',
      'aria-describedby': 'amount-addon', placeholder: 'Tips Amount' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :comment, class: 'sr-only' %>
    <div class="input-group mb-2">
      <div class="input-group-prepend" id="comment-addon">
        <span class="input-group-text far fa-edit"></span>
      </div>
      <%= f.text_area :comment, class: 'form-control form-control-lg', 'aria-label': 'comment', 'aria-described-by': 'comment-addon', 
      placeholder: 'Any additional info you\'d like to add. E.g. "Today was not good. Due to a bomb threat the store had to close early"' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
  <hr>
</div>

app/views/tips/edit.html.erb
<div class="text-center">
  <h2>Edit Tip</h2>
</div>

  <%= render 'form', tip: @tip %>

  <%= link_to 'Show', user_tip_path %> |
  <%= link_to 'Back', url_for(:back) %>

app/views/tips/index.html.erb
<div class="text-center">
  <h2>All Your Tips</h2>
  <%= link_to 'New Tip', new_user_tip_path %>
</div>
<hr>

<div class="container">
  <div class="row">
    <% @tips.each do |tip| %>
    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">


      <div class="card mx-auto my-1">
        <h5 class="card-header">
          R<%= tip.amount.round(2) %>
        </h5>
        <div class="card-body">
          <h5 class="card-title text-muted"><%= tip.date %></h5>
          <h6 class="card-subtitle pb-2"><%= tip.hours %> Hours worked</h6>
          <h6 class="card-text">Comment?
            <% if tip.comment.length > 0 %>
              Yes
              <% else %>
              No
              <% end %>
            </h6>
          <%= link_to 'Show', user_tip_path(tip.user, tip), class: 'card-link' %>
          <%= link_to 'Edit', edit_user_tip_path(tip.user, tip), class: 'card-link' %>
          <%= link_to 'Destroy', user_tip_path(tip.user, tip), class: 'card-link', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/tips/new.html.erb
<div class="text-center">
  <h2>Add a tip</h2>
</div>

<%= render 'form', tip: @tip %>

<%= link_to 'Back', url_for(:back) %>

app/views/tips/show.html.erb
<p>
  <strong>User:</strong>
  <%= @tip.user.first_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @tip.date %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @tip.hours %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @tip.amount.round(2) %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @tip.comment %>
</p>

<%= link_to 'Edit', edit_user_tip_path(@user, @tip) %> |
<%= link_to 'Back', url_for(:back) %>

app/views/users/_form.html.erb
<div class="container">
  <hr>
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :first_name, class: 'sr-only' %>
      <div class="input-group mb-2">
        <div class="input-group-prepend" id="first_name-addon">
          <span class="input-group-text">First Name</span>
        </div>
        <%= form.text_field :first_name, class: 'form-control form-control-lg', 'aria-label': 'first_name', 'aria-describedby': 'first_name-addon', placeholder: 'John \ Jane' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :last_name, class: 'sr-only' %>
      <div class="input-group mb-2">
        <div class="input-group-prepend" id="last_name-addon">
          <span class="input-group-text">Last Name</span>
        </div>
        <%= form.text_field :last_name, class: 'form-control form-control-lg', 'aria-label': 'last_name', 'aria-described-by': 'last_name-addon', placeholder: 'Doe' %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h2>Edit User Details</h2>
</div>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', url_for(:back) %>

app/views/users/index.html.erb
<div class="text-center">
  <h2>All Users</h2>
</div>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="text-center">
  <h2>New User</h2>
</div>

<%= render 'form', user: @user %>

<%= link_to 'Home', landing_pages_home_path %>

app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', url_for(:back) %>